"""
Issue #1 — Convert pretrained_shl_coarse.keras to INT8 TFLite.

Outputs:
  model/co2_beacon_int8.tflite
  firmware/beacon_inference/model_data.h

Usage (from repo root):
  python notebooks/scripts/convert_to_tflite.py
"""

import os
import sys
import subprocess
import numpy as np
import tensorflow as tf

# ── Paths ────────────────────────────────────────────────────────────────────
REPO_ROOT   = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
KERAS_PATH  = os.path.join(REPO_ROOT, "data", "processed", "pretrained_shl_coarse.keras")
NPZ_PATH    = os.path.join(REPO_ROOT, "data", "processed", "features",
                           "baseline_features_v3_segment_split_train_val_test.npz")
TFLITE_PATH = os.path.join(REPO_ROOT, "model", "co2_beacon_int8.tflite")
HEADER_PATH = os.path.join(REPO_ROOT, "firmware", "beacon_inference", "model_data.h")

# Number of calibration batches for representative dataset
N_CALIB = 200


def load_norm_stats(npz):
    """Load mu/sigma stored directly in the npz (shape (1,1,7) → (7,))."""
    mu    = np.squeeze(npz["mu"])     # (7,)
    sigma = np.squeeze(npz["sigma"])  # (7,)
    return mu, sigma


def make_representative_dataset(X_train, mu, sigma, n_samples=N_CALIB):
    """
    Yield normalized float32 windows for INT8 calibration.
    Input shape expected by model: (1, 125, 7, 1)
    """
    indices = np.random.choice(len(X_train), size=n_samples, replace=False)

    def generator():
        for i in indices:
            window = X_train[i]           # (125, 7, 1)
            # Z-score normalise using frozen train-split stats
            window_norm = (window[..., 0] - mu) / sigma   # (125, 7)
            window_norm = window_norm[..., np.newaxis]     # (125, 7, 1)
            yield [window_norm.astype(np.float32)[np.newaxis]]  # (1,125,7,1)

    return generator


def verify_int8(tflite_path):
    """Check that all ops are INT8 (no float kernels)."""
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()
    details = interpreter.get_tensor_details()
    float_tensors = [d for d in details if d["dtype"] == np.float32]
    # Input/output scale tensors are expected to be float — filter them
    internal_float = [d for d in float_tensors
                      if d["name"] not in ("serving_default_input_1:0",)]
    return len(internal_float) == 0, float_tensors


def run_accuracy_check(tflite_path, X_test, y_test, mu, sigma):
    """Run INT8 interpreter on test split and report accuracy."""
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()
    inp  = interpreter.get_input_details()[0]
    outp = interpreter.get_output_details()[0]

    scale_in  = inp["quantization_parameters"]["scales"][0]
    zp_in     = inp["quantization_parameters"]["zero_points"][0]
    scale_out = outp["quantization_parameters"]["scales"][0]
    zp_out    = outp["quantization_parameters"]["zero_points"][0]

    correct = 0
    for i in range(len(X_test)):
        window = X_test[i][..., 0]                     # (125, 7)
        window_norm = (window - mu) / sigma
        window_norm = window_norm[np.newaxis, :, :, np.newaxis]  # (1,125,7,1)

        # Quantise to INT8
        q = np.round(window_norm / scale_in + zp_in).clip(-128, 127).astype(np.int8)
        interpreter.set_tensor(inp["index"], q)
        interpreter.invoke()
        out_q = interpreter.get_tensor(outp["index"])   # (1,5) INT8
        out_f = (out_q.astype(np.float32) - zp_out) * scale_out
        pred  = np.argmax(out_f)
        if pred == y_test[i]:
            correct += 1

    return correct / len(X_test)


def generate_header(tflite_path, header_path):
    """Run xxd to produce a C byte-array header."""
    # xxd -i produces:   unsigned char <name>[] = { ... };
    result = subprocess.run(
        ["xxd", "-i", os.path.basename(tflite_path)],
        capture_output=True, text=True,
        cwd=os.path.dirname(tflite_path)
    )
    if result.returncode != 0:
        print(f"[WARN] xxd failed: {result.stderr}")
        return

    content = result.stdout
    # Rename variable to g_model_data / g_model_data_len for Arduino
    content = content.replace(
        "unsigned char co2_beacon_int8_tflite[]",
        "const unsigned char g_model_data[]"
    ).replace(
        "unsigned int co2_beacon_int8_tflite_len",
        "const unsigned int g_model_data_len"
    )

    header = (
        "// model_data.h — auto-generated by notebooks/scripts/convert_to_tflite.py\n"
        "// DO NOT EDIT MANUALLY — regenerate if model changes\n"
        "#pragma once\n\n"
        + content
    )
    with open(header_path, "w") as f:
        f.write(header)
    print(f"[OK]  Header written: {header_path}")


def main():
    print("=" * 60)
    print("Issue #1 — TFLite INT8 conversion")
    print("=" * 60)

    # ── Load model ────────────────────────────────────────────────
    if not os.path.exists(KERAS_PATH):
        sys.exit(f"[ERROR] Keras model not found: {KERAS_PATH}")
    print(f"[OK]  Loading model: {KERAS_PATH}")
    model = tf.keras.models.load_model(KERAS_PATH)
    model.summary()

    # ── Load dataset ──────────────────────────────────────────────
    if not os.path.exists(NPZ_PATH):
        sys.exit(f"[ERROR] NPZ not found: {NPZ_PATH}")
    print(f"\n[OK]  Loading dataset: {NPZ_PATH}")
    npz     = np.load(NPZ_PATH)
    X_train = npz["X_train"]   # (N, 125, 7, 1)
    X_test  = npz["X_test"]
    y_test  = npz["y_test"]
    mu, sigma = load_norm_stats(npz)
    print(f"      X_train shape: {X_train.shape}")
    print(f"      mu:    {mu}")
    print(f"      sigma: {sigma}")

    # ── Convert ───────────────────────────────────────────────────
    print("\n[...] Converting to INT8 TFLite...")
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = make_representative_dataset(X_train, mu, sigma)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    os.makedirs(os.path.dirname(TFLITE_PATH), exist_ok=True)
    with open(TFLITE_PATH, "wb") as f:
        f.write(tflite_model)

    size_kb = os.path.getsize(TFLITE_PATH) / 1024
    print(f"[OK]  Saved: {TFLITE_PATH}")
    print(f"      Size: {size_kb:.1f} KB", end="")
    if size_kb <= 100:
        print("  ✅ (≤ 100 KB)")
    else:
        print("  ⚠  WARNING: exceeds 100 KB target")

    # ── Verify INT8 ───────────────────────────────────────────────
    print("\n[...] Verifying INT8 quantization...")
    is_int8, float_tensors = verify_int8(TFLITE_PATH)
    if is_int8:
        print("[OK]  All ops are INT8 ✅")
    else:
        print(f"[WARN] {len(float_tensors)} float tensor(s) found — partial quantization")

    # ── Accuracy check ────────────────────────────────────────────
    print("\n[...] Running accuracy check on test split...")
    acc = run_accuracy_check(TFLITE_PATH, X_test, y_test, mu, sigma)
    print(f"      INT8 test accuracy: {acc*100:.1f}%", end="")
    if acc >= 0.90:
        print("  ✅ (≥ 90%)")
    else:
        print("  ⚠  WARNING: below 90% target")

    # ── Generate header ───────────────────────────────────────────
    print("\n[...] Generating model_data.h via xxd...")
    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    generate_header(TFLITE_PATH, HEADER_PATH)

    print("\n" + "=" * 60)
    print("Issue #1 COMPLETE")
    print(f"  TFLite model : {TFLITE_PATH}")
    print(f"  C header     : {HEADER_PATH}")
    print(f"  Size         : {size_kb:.1f} KB")
    print(f"  Accuracy     : {acc*100:.1f}%")
    print("=" * 60)


if __name__ == "__main__":
    main()
