"""
Issue #2 — Export normalization stats to firmware/beacon_inference/norm_stats.h

Reads mu and sigma directly from the .npz file (keys 'mu' and 'sigma').
Squeezes from shape (1,1,7) to (7,) before writing.

Usage (from repo root):
  python notebooks/scripts/export_norm_stats.py
"""

import os
import sys
import numpy as np
from datetime import datetime

# ── Paths ────────────────────────────────────────────────────────────────────
REPO_ROOT   = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
NPZ_PATH    = os.path.join(REPO_ROOT, "data", "processed",
                           "baseline_features_v4_segment_split_train_val_test.npz")
HEADER_PATH = os.path.join(REPO_ROOT, "firmware", "beacon_inference", "norm_stats.h")

# Channel names — must match model input order
CHANNELS = ["ax", "ay", "az", "gx", "gy", "gz", "pressure_hpa"]

# Confirmed values — updated after v4 dataset rebuild (200-sample windows)
# Set to None to skip cross-check on first run; populate after verifying output.
CONFIRMED_MU    = None
CONFIRMED_SIGMA = None


def format_float_array(name, values, channels):
    """Format a C float array with per-element channel comments."""
    lines = [f"static const float {name}[{len(values)}] = {{"]
    for i, (v, ch) in enumerate(zip(values, channels)):
        comma = "," if i < len(values) - 1 else ""
        lines.append(f"    {v:.8f}f{comma}  // [{i}] {ch}")
    lines.append("};")
    return "\n".join(lines)


def main():
    print("=" * 60)
    print("Issue #2 — Export normalization stats to norm_stats.h")
    print("=" * 60)

    # ── Load npz ──────────────────────────────────────────────────
    if not os.path.exists(NPZ_PATH):
        sys.exit(f"[ERROR] NPZ not found: {NPZ_PATH}")
    print(f"[OK]  Loading: {NPZ_PATH}")
    npz = np.load(NPZ_PATH)

    if "mu" not in npz or "sigma" not in npz:
        sys.exit("[ERROR] 'mu' and/or 'sigma' keys not found in npz. "
                 "Check the dataset file.")

    mu    = np.squeeze(npz["mu"]).astype(np.float64)     # (7,)
    sigma = np.squeeze(npz["sigma"]).astype(np.float64)  # (7,)

    print(f"\n      Raw mu shape:    {npz['mu'].shape}  → squeezed to {mu.shape}")
    print(f"      Raw sigma shape: {npz['sigma'].shape}  → squeezed to {sigma.shape}")

    if mu.shape != (7,) or sigma.shape != (7,):
        sys.exit(f"[ERROR] Expected shape (7,) after squeeze, got mu={mu.shape}, sigma={sigma.shape}")

    # ── Print values ──────────────────────────────────────────────
    print("\n      Channel       mu              sigma")
    print("      " + "-" * 48)
    for i, ch in enumerate(CHANNELS):
        print(f"      [{i}] {ch:<14}  {mu[i]:>12.7f}   {sigma[i]:>12.7f}")

    # ── Cross-check against confirmed values ──────────────────────
    if CONFIRMED_MU is not None and CONFIRMED_SIGMA is not None:
        print("\n[...] Cross-checking against confirmed values...")
        mu_ok    = np.allclose(mu,    CONFIRMED_MU,    atol=1e-4)
        sigma_ok = np.allclose(sigma, CONFIRMED_SIGMA, atol=1e-4)
        if mu_ok and sigma_ok:
            print("[OK]  Values match confirmed constants ✅")
        else:
            print("[WARN] Values differ from confirmed constants — verify dataset version")
            for i, ch in enumerate(CHANNELS):
                mu_diff = abs(mu[i] - CONFIRMED_MU[i])
                s_diff  = abs(sigma[i] - CONFIRMED_SIGMA[i])
                if mu_diff > 1e-4 or s_diff > 1e-4:
                    print(f"       [{i}] {ch}: mu_diff={mu_diff:.6f}, sigma_diff={s_diff:.6f}")
    else:
        print("\n[INFO] Cross-check skipped — update CONFIRMED_MU/SIGMA after verifying output.")

    # ── Write header ──────────────────────────────────────────────
    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)

    mu_array    = format_float_array("NORM_MU",    mu,    CHANNELS)
    sigma_array = format_float_array("NORM_SIGMA", sigma, CHANNELS)

    header = f"""\
// norm_stats.h — auto-generated by notebooks/scripts/export_norm_stats.py
// Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
// Source:    baseline_features_v4_segment_split_train_val_test.npz
//
// DO NOT EDIT MANUALLY.
// To regenerate: python notebooks/scripts/export_norm_stats.py
//
// Channel order: ax, ay, az, gx, gy, gz, pressure_hpa  (indices 0-6)
// Mode order:    train(0), subway(1), car(2), bus(3), walk(4)
//
// Usage in firmware:
//   x_norm = (x_raw - NORM_MU[c]) / NORM_SIGMA[c];
//
// Accelerometer biases (subtract BEFORE normalization):
//   ACC_BIAS_X = -0.1926f   ACC_BIAS_Y = -0.1975f   ACC_BIAS_Z = -0.3472f
#pragma once

{mu_array}

{sigma_array}
"""

    with open(HEADER_PATH, "w") as f:
        f.write(header)

    print(f"\n[OK]  Header written: {HEADER_PATH}")
    print("\n" + "=" * 60)
    print("Issue #2 COMPLETE")
    print("=" * 60)

    # ── Print generated file ──────────────────────────────────────
    print("\n--- norm_stats.h contents ---\n")
    print(header)


if __name__ == "__main__":
    main()
