// norm_stats.h — auto-generated by notebooks/scripts/export_norm_stats.py
// Generated: 2026-02-26 19:16:44
// Source:    baseline_features_v4_segment_split_train_val_test.npz
//
// DO NOT EDIT MANUALLY.
// To regenerate: python notebooks/scripts/export_norm_stats.py
//
// Channel order: ax, ay, az, gx, gy, gz, pressure_hpa  (indices 0-6)
// Mode order:    train(0), subway(1), car(2), bus(3), walk(4)
//
// Usage in firmware:
//   x_norm = (x_raw - NORM_MU[c]) / NORM_SIGMA[c];
//
// Accelerometer biases (subtract BEFORE normalization):
//   ACC_BIAS_X = -0.1926f   ACC_BIAS_Y = -0.1975f   ACC_BIAS_Z = -0.3472f
#pragma once

static const float NORM_MU[7] = {
    -7.79250193f,  // [0] ax
    2.07272148f,  // [1] ay
    4.27278090f,  // [2] az
    0.41056770f,  // [3] gx
    -0.15372396f,  // [4] gy
    0.16609201f,  // [5] gz
    1014.45190430f  // [6] pressure_hpa
};

static const float NORM_SIGMA[7] = {
    1.59938383f,  // [0] ax
    1.88753140f,  // [1] ay
    3.04334497f,  // [2] az
    18.63519859f,  // [3] gx
    9.55679989f,  // [4] gy
    8.78757954f,  // [5] gz
    8.03807831f  // [6] pressure_hpa
};
